### ISSUE TITLE
Thread minimal does not work with Minar 1.0.1

### ISSUE THREAD

**Issue by mlnx** [ARMmbed/mbed-thread-jn517x-example#1] opened 2016-01-28 18:26 UTC
This problem was raised some time ago and we are now able to reproduce.
It seems there is something wrong with the latest version of Minar (1.0.1), as there is no radio activity. Everything works as expected when using Minar 1.0.0.
This is the diff between versions:

``` 
diff --git a/source/minar.cpp b/source/minar.cpp
index c05a54a..4c9c1b2 100644
--- a/source/minar.cpp
+++ b/source/minar.cpp
@@ -387,10 +387,11 @@ int minar::SchedulerData::start(){
                 //
                 // We have to perform this update with interrupts disabled
                 // because we use last_dispatch for sorting dispatch_tree
-                if(dispatch_tree.get_num_elements() > 0)
-                    last_dispatch = smallestTimeIncrement(last_dispatch, now, (dispatch_tree.get_root())->call_before);
-                else
-                    last_dispatch = smallestTimeIncrement(last_dispatch, now, next->call_before);
+                //
+                // next is guaranteed to be the next item in must-execute-by
+                // order, since the callback list is sorted in must-execute-by
+                // order.
+                last_dispatch = smallestTimeIncrement(last_dispatch, now, next->call_before);
 
                 const minar::tick_t lag = wrapTime(now - last_dispatch);
                 if(lag > Warn_Lag_Ticks)
```

ARM Internal Ref: IOTSFW-1828

**Comment by LiyouZhou** [comment] 2016-01-28 18:30
Investigation notes:
I started printing variables in minar, here are the logs.

*Before*
```
MINAR: n 1 now 6 ld 0 next 2
MINAR: n 2 now 270 ld 2 next 94root 367
MINAR: n 1 now 739 ld 270 next 367
MINAR: n 1 now 837 ld 367 next 694
MINAR: n 2 now 935 ld 694 next 852root 1021
MINAR: n 1 now 1057 ld 935 next 1021
MINAR: n 1 now 1161 ld 1021 next 1348
MINAR: n 1 now 1267 ld 1161 next 1675
MINAR: n 1 now 1373 ld 1267 next 2002
MINAR: n 2 now 1479 ld 1373 next 1389root 2329
MINAR: n 1 now 1610 sleep 1620
MINAR: n 2 now 1697 ld 1610 next 1620root 2329
MINAR: n 1 now 1828 ld 1697 next 2329
MINAR: n 1 now 1934 ld 1828 next 2656
MINAR: n 1 now 2040 ld 1934 next 2983
MINAR: n 1 now 2146 ld 2040 next 3310
MINAR: n 1 now 2252 ld 2146 next 3637
MINAR: n 2 now 2358 ld 2252 next 2268root 3964
MINAR: n 1 now 2489 ld 2358 next 3964
MINAR: n 1 now 2595 ld 2489 next 4291
MINAR: n 1 now 2701 ld 2595 next 4618
MINAR: n 1 now 2807 ld 2701 next 4945
MINAR: n 1 now 2914 ld 2807 next 5272
MINAR: n 1 now 3020 ld 2914 next 5599
MINAR: n 1 now 3126 sleep 3136
MINAR: n 2 now 3213 ld 3126 next 3136root 5926
MINAR: n 1 now 3344 ld 3213 next 5926
MINAR: n 1 now 3450 ld 3344 next 6253
MINAR: n 1 now 3556 ld 3450 next 6580
MINAR: n 1 now 3662 ld 3556 next 6907
MINAR: n 1 now 3768 sleep 7234
MINAR: n 1 now 76 ld 3768 next 7234
MINAR: n 1 now 177 ld 7234 next 7561
MINAR: n 1 now 280 ld 7561 next 7888
MINAR: n 1 now 384 ld 7888 next 8215
MINAR: n 1 now 487 ld 8215 next 8542
MINAR: n 1 now 591 ld 8542 next 8869
MINAR: n 1 now 694 ld 8869 next 9196
MINAR: n 1 now 798 ld 9196 next 9523
MINAR: n 2 now 901 ld 9523 next 9850root 874
MINAR: n 2 now 1026 ld 874 next 874root 10177
MINAR: n 1 now 1154 sleep 10177
MINAR: n 1 now 1244 sleep 10177
MINAR: n 1 now 1334 sleep 10177
MINAR: n 1 now 1424 sleep 10177
MINAR: n 1 now 1513 sleep 10177
MINAR: n 1 now 1603 sleep 10177
MINAR: n 1 now 1693 sleep 10177
MINAR: n 1 now 1783 sleep 10177
MINAR: n 1 now 1873 sleep 10177
MINAR: n 1 now 1962 sleep 10177
MINAR: n 1 now 2052 sleep 10177
MINAR: n 1 now 2142 sleep 10177
MINAR: n 1 now 2232 sleep 10177
MINAR: n 1 now 2322 sleep 10177
MINAR: n 2 now 2412 ld 2322 next 2390root 10177
MINAR: n 1 now 2954 sleep 10177
MINAR: n 1 now 3044 sleep 10177
MINAR: n 1 now 3134 sleep 10177
MINAR: n 1 now 3224 sleep 10177
MINAR: n 1 now 3314 sleep 10177
MINAR: n 1 now 3404 sleep 10177
MINAR: n 1 now 3494 sleep 10177
MINAR: n 1 now 3583 sleep 10177
MINAR: n 1 now 3673 sleep 10177
MINAR: n 1 now 3763 sleep 10177
MINAR: n 1 now 3853 sleep 10177
MINAR: n 2 now 3943 ld 3853 next 3907root 10177
MINAR: n 1 now 4076 sleep 10177
MINAR: n 1 now 4166 sleep 10177
MINAR: n 1 now 4256 sleep 10177
MINAR: n 1 now 4346 sleep 10177
MINAR: n 1 now 4436 sleep 10177
MINAR: n 1 now 4525 sleep 10177
MINAR: n 1 now 4615 sleep 10177
MINAR: n 1 now 4705 sleep 10177
MINAR: n 1 now 4795 sleep 10177
MINAR: n 1 now 4885 sleep 10177
MINAR: n 1 now 4975 sleep 10177
MINAR: n 1 now 5064 sleep 10177
MINAR: n 1 now 5154 sleep 10177
MINAR: n 1 now 5244 sleep 10177
MINAR: n 1 now 5334 sleep 10177
MINAR: n 1 now 5424 sleep 10177
MINAR: n 2 now 5514 ld 5424 next 5455root 10177
MINAR: n 1 now 5647 sleep 10177
MINAR: n 1 now 5737 sleep 10177
MINAR: n 1 now 5827 sleep 10177
MINAR: n 1 now 5917 sleep 10177
MINAR: n 1 now 6006 sleep 10177
MINAR: n 1 now 6096 sleep 10177
MINAR: n 1 now 6186 sleep 10177
MINAR: n 1 now 6276 sleep 10177
MINAR: n 1 now 6366 sleep 10177
MINAR: n 1 now 6456 sleep 10177
MINAR: n 1 now 6545 sleep 10177
MINAR: n 1 now 6635 sleep 10177
MINAR: n 1 now 6725 sleep 10177
MINAR: n 1 now 6815 sleep 10177
MINAR: n 1 now 6838 sleep 10177
MINAR: n 2 now 6917 ld 6838 next 6894root 10177
MINAR: n 1 now 7050 ld 6917 next 10177
MINAR: n 1 now 7159 sleep 10504
MINAR: n 1 now 7249 ld 7159 next 10504
MINAR: n 1 now 7358 sleep 10831
MINAR: n 1 now 7447 sleep 10831
MINAR: n 1 now 7537 sleep 10831
MINAR: n 1 now 7627 ld 7537 next 10831
MINAR: n 1 now 7736 sleep 11158
MINAR: n 1 now 7826 sleep 11158
MINAR: n 1 now 7916 ld 7826 next 11158
MINAR: n 1 now 8024 sleep 11485
MINAR: n 1 now 8114 sleep 11485
MINAR: n 1 now 8204 sleep 11485
```

*After*
```
MINAR: n 1 now 6 ld 0 next 2
MINAR: n 2 now 278 ld 2 next 95
MINAR: n 1 now 744 ld 95 next 368
MINAR: n 1 now 839 ld 368 next 695
MINAR: n 2 now 937 ld 695 next 855
MINAR: n 1 now 1035 ld 855 next 1022
MINAR: n 1 now 1139 ld 1022 next 1349
MINAR: n 1 now 1245 ld 1139 next 1676
MINAR: n 1 now 1351 ld 1245 next 2003
MINAR: n 2 now 1457 ld 1351 next 1367
MINAR: n 1 now 1564 ld 1367 next 2330
MINAR: n 2 now 1670 ld 1564 next 1621
MINAR: n 1 now 1776 ld 1621 next 2657
MINAR: n 1 now 1882 ld 1776 next 2984
MINAR: n 1 now 1988 ld 1882 next 3311
MINAR: n 1 now 2094 ld 1988 next 3638
MINAR: n 2 now 2201 ld 2094 next 2110
MINAR: n 1 now 2307 ld 2110 next 3965
MINAR: n 1 now 2413 ld 2307 next 4292
MINAR: n 1 now 2519 ld 2413 next 4619
MINAR: n 1 now 2625 ld 2519 next 4946
MINAR: n 1 now 2731 ld 2625 next 5273
MINAR: n 1 now 2838 ld 2731 next 5600
MINAR: n 1 now 2944 ld 2838 next 5927
MINAR: n 1 now 3050 ld 2944 next 6254
MINAR: n 2 now 3156 ld 3050 next 3138
MINAR: n 1 now 3262 sleep 6581
MINAR: n 1 now 76 sleep 6581
MINAR: n 1 now 158 ld 6581 next 6581
MINAR: n 1 now 261 ld 6581 next 6908
MINAR: n 1 now 365 ld 6908 next 7235
MINAR: n 1 now 468 ld 7235 next 7562
MINAR: n 1 now 572 ld 7562 next 7889
MINAR: n 1 now 675 ld 7889 next 8216
MINAR: n 1 now 779 ld 8216 next 8543
MINAR: n 1 now 882 ld 8543 next 8870
MINAR: n 1 now 985 ld 8870 next 9197
MINAR: n 1 now 1089 ld 9197 next 9524
MINAR: n 1 now 1195 ld 9524 next 9851
MINAR: n 1 now 1301 ld 9851 next 10178
MINAR: n 2 now 1410 ld 10178 next 10505
MINAR: n 2 now 1522 ld 10505 next 10832
MINAR: n 2 now 1633 ld 10832 next 11159
MINAR: n 2 now 1745 ld 11159 next 11486
MINAR: n 2 now 1856 ld 11486 next 11813
MINAR: n 2 now 1968 ld 11813 next 12140
MINAR: n 2 now 2080 ld 12140 next 12467
MINAR: n 2 now 2191 ld 12467 next 12794
MINAR: n 2 now 2303 ld 12794 next 13121
MINAR: n 2 now 2414 ld 13121 next 13448
MINAR: n 2 now 2526 ld 13448 next 13775
MINAR: n 2 now 2638 ld 13775 next 14102
MINAR: n 2 now 2749 ld 14102 next 14429
MINAR: n 2 now 2861 ld 14429 next 14756
MINAR: n 2 now 2973 ld 14756 next 15083
MINAR: n 2 now 3084 ld 15083 next 15410
MINAR: n 2 now 3196 ld 15410 next 15737
MINAR: n 2 now 3307 ld 15737 next 16064
MINAR: n 2 now 3419 ld 16064 next 16391
MINAR: n 2 now 3531 ld 16391 next 16718
MINAR: n 2 now 3642 ld 16718 next 17045
MINAR: n 2 now 3754 ld 17045 next 17372
MINAR: n 2 now 3865 ld 17372 next 17699
MINAR: n 2 now 3977 ld 17699 next 18026
MINAR: n 2 now 4089 ld 18026 next 18353
MINAR: n 2 now 4200 ld 18353 next 18680
MINAR: n 2 now 4312 ld 18680 next 19007
MINAR: n 2 now 4423 ld 19007 next 19334
MINAR: n 2 now 4535 ld 19334 next 19661
MINAR: n 2 now 4647 ld 19661 next 19988
MINAR: n 2 now 4758 ld 19988 next 20315
MINAR: n 2 now 4870 ld 20315 next 20642
MINAR: n 2 now 4981 ld 20642 next 20969
MINAR: n 2 now 5093 ld 20969 next 21296
MINAR: n 2 now 5205 ld 21296 next 21623
MINAR: n 2 now 5316 ld 21623 next 21950
MINAR: n 2 now 5428 ld 21950 next 22277
MINAR: n 2 now 5539 ld 22277 next 22604
MINAR: n 2 now 5651 ld 22604 next 22931
MINAR: n 2 now 5763 ld 22931 next 23258
MINAR: n 2 now 5874 ld 23258 next 23585
MINAR: n 2 now 5986 ld 23585 next 23912
MINAR: n 2 now 6097 ld 23912 next 24239
MINAR: n 2 now 6209 ld 24239 next 24566
MINAR: n 2 now 6220 ld 24566 next 24893
MINAR: n 2 now 6220 ld 24893 next 25220
MINAR: n 2 now 6220 ld 25220 next 25547
MINAR: n 2 now 6220 ld 25547 next 25874
MINAR: n 2 now 6220 ld 25874 next 26201
MINAR: n 2 now 6220 ld 26201 next 26528
MINAR: n 2 now 6220 ld 26528 next 26855
MINAR: n 2 now 6220 ld 26855 next 27182
MINAR: n 2 now 6220 ld 27182 next 27509
MINAR: n 2 now 6220 ld 27509 next 27836
MINAR: n 2 now 6220 ld 27836 next 28163
MINAR: n 2 now 6220 ld 28163 next 28490
MINAR: n 2 now 6220 ld 28490 next 28817
MINAR: n 2 now 6220 ld 28817 next 29144
MINAR: n 2 now 6220 ld 29144 next 29471
MINAR: n 2 now 6220 ld 29471 next 29798
MINAR: n 2 now 6220 ld 29798 next 30125
MINAR: n 2 now 6220 ld 30125 next 30452
MINAR: n 2 now 6220 ld 30452 next 30779
MINAR: n 2 now 6220 ld 30779 next 31106
MINAR: n 2 now 6220 ld 31106 next 31433
MINAR: n 2 now 6220 ld 31433 next 31760
MINAR: n 2 now 6220 ld 31760 next 32087
MINAR: n 2 now 6220 ld 32087 next 32414
MINAR: n 2 now 6220 ld 32414 next 32741
MINAR: n 2 now 6220 ld 32741 next 33068
MINAR: n 2 now 6220 ld 33068 next 33395
MINAR: n 2 now 6220 ld 33395 next 33722
MINAR: n 2 now 6220 ld 33722 next 34049
MINAR: n 2 now 6220 ld 34049 next 34376
MINAR: n 2 now 6220 ld 34376 next 34703
MINAR: n 2 now 6220 ld 34703 next 35030
MINAR: n 2 now 6220 ld 35030 next 35357
MINAR: n 2 now 6220 ld 35357 next 35684
MINAR: n 2 now 6220 ld 35684 next 36011
MINAR: n 2 now 6220 ld 36011 next 36338
MINAR: n 2 now 6220 ld 36338 next 36665
MINAR: n 2 now 6220 ld 36665 next 36992
MINAR: n 2 now 6220 ld 36992 next 37319
MINAR: n 2 now 6220 ld 37319 next 37646
MINAR: n 2 now 6220 ld 37646 next 37973
MINAR: n 2 now 6220 ld 37973 next 38300
MINAR: n 2 now 6220 ld 38300 next 38627
MINAR: n 2 now 6220 ld 38627 next 38954
MINAR: n 2 now 6220 ld 38954 next 39281
MINAR: n 2 now 6220 ld 39281 next 39608
MINAR: n 2 now 6220 ld 39608 next 39935
MINAR: n 2 now 6220 ld 39935 next 40262
```

If you look at the variable `now`, it comes from `minar::platform::getTime()` which returns `lp_ticker_read()`. It should be a monotonously increasing timer which overflows at minar::platform::Time_Base.

There are two strange things with this variable. The two things may be related or not.

1. It goes up to about 3000 then suddenly jumps back to 100
1. In the *after* case, the timer goes up to 6220 and gets stuck.

**Comment by LiyouZhou** [comment] 2016-01-28 18:31
Tracking this problem to the following `lp_ticker` implementation:
```
/*
 *  Low Power Tick Timer read tick function
 */
uint32_t lp_ticker_read(void) {
    lp_ticker_init();
    uint32_t count;
    uint32_t control_bit;

    control_bit = 1 << WAKE_TIM;

    /* Read current count */
    if((u32REG_SysRead(REG_SYS_WK_TS) & control_bit) != 0) {
        printf("[!]");
        count = lp_count + (lp_set_count - lptimer_read(WAKE_TIM));
    }
    else {
        count = lp_count;
    }
    return  count;
}
```

if `(u32REG_SysRead(REG_SYS_WK_TS) & control_bit)` is not true then the else branch is taken where `lp_count` is returned. And `lp_count` is not incrementing.

I don't understand enough about the implementation to deduce any further.

**Comment by LiyouZhou** [comment] 2016-01-28 18:32
New observation,

I was playing around with printf() in minar, causing timing of functions to change, I was able to trigger the "timer stuck" behaviour event in the before case.

Meaning: This bug is timing related, it's dependency on minar version is a coincidence.

**Comment by LiyouZhou** [comment] 2016-01-28 18:32
Suggestion: Can NXP investigate the timer jump back and getting stuck bugs?  With a well behaved timer, minar should behave correctly.

Insert printf("now %lu ", now); after https://github.com/ARMmbed/minar/blob/master/source/minar.cpp#L242 to print the "now" variable.

**Comment by mlnx** [comment] 2016-01-28 18:35
@bangaragirinxp Could you please review the information shown in this ticket and check the implementation of the timer?

**Comment by bangaragirinxp** [comment] 2016-01-29 09:04
To understand, can you please clarify the following functions:
a. lp_tick_read function - It should return the current count of free running counter. is this correct?
b. get_match_value - It should return the next match value set at which LP ticker will generate the interrupt. Is this correct?

**Comment by bangaragirinxp** [comment] 2016-01-29 10:10
Please clarify Time_Base value field. Is this the clock frequency value of the LP Ticker timer? Or is this the maximum count that LP Ticker can support?

**Comment by bangaragirinxp** [comment] 2016-01-29 11:47
In JN5179 device, LP Ticker is down counter. We have implemented LPTicker timer using 2 HW units.
a. 1 LPTicker module as free running ticker counter
b. Second LPTicker module as counter timer which provides interrupt with the required match value
The changes are committed in - https://github.com/ARMmbed/mbed-hal-nxp-jn517x/commit/61549f2a321b47408b1f1a3fe9bacaf7596047bb
Please use this & check on your board & let us know the feedback.
We observe that the now value is monotonously incremented. With mbed-thread-minimal application, we have the following observations:
- We can observe the packets over the air, but the JN5179 device is not getting connected to network (not visisble in mDS on host PC)
- When we enable the print in minar.cpp to print now value (as suggested by LiYouZhou), we can see that the device is connected to mDS
So it looks like still some timing issue exists.

**Comment by LiyouZhou** [comment] 2016-01-29 21:56
@bangaragirinxp I can confirm that I see s monotonous increasing timer. Minar seem to behave as expected as well.

As to your issue. I was wondering if it would be related to https://github.com/ARMmbed/sal-stack-nanostack-eventloop/issues/18.

I would suggest capturing the packets and decoding them to see what are the deferences? Of no obvious mistake can be found from the packets, we might need to involve mDS folks to take a look.

**Comment by mlnx** [comment] 2016-02-01 19:37
@bangaragirinxp we need your help to investigate this further.
Could you please share Wireshark radio sniffer captures comparing the two implementations (minar 1.0.0 and 1.0.1)?

**Comment by bangaragirinxp** [comment] 2016-02-02 04:12
[Ubisys_logs.zip](https://github.com/ARMmbed/mbed-thread-jn517x-example/files/113402/Ubisys_logs.zip)
Please find the ubisys sniffer logs for the two scenarios (with print & without print in minar).

**Comment by mlnx** [comment] 2016-02-09 10:08
@bangaragirinxp could you please share the scripts that let us reproduce this behaviour?

**Comment by bangaragirinxp** [comment] 2016-02-09 10:19
[setup_minar_1_0_1.txt](https://github.com/ARMmbed/mbed-thread-jn517x-example/files/122895/setup_minar_1_0_1.txt)

**Comment by mlnx** [comment] 2016-02-09 11:39
I'm afraid I'm not able to see any radio activity with this batch script. Could you please confirm?

**Comment by bangaragirinxp** [comment] 2016-02-10 06:52
Can you please try with earlier script which you were using, but use the updates from dev_nxp_main branch for components in mbed-hal-nxpdk5-jn517x & mbed-hal-nxp-jn517x?

**Comment by mlnx** [comment] 2016-02-10 16:13
Please provide scripts to reproduce the builds (with and without printf)

**Comment by bangaragirinxp** [comment] 2016-02-11 07:09
Please find the script.
[mbed_thread_minimal_build.txt](https://github.com/ARMmbed/mbed-thread-jn517x-example/files/126003/mbed_thread_minimal_build.txt)

**Comment by bangaragirinxp** [comment] 2016-02-11 07:11
If you want to try with print, please add a print in minar.cpp as suggested by LiYouZhou

**Comment by mlnx** [comment] 2016-02-12 16:29
Thanks for the info. I've managed to reproduce the behaviour as reported. There seems to be a timing issue (not clear now what it's causing that).

* Case 1: JN5x end-node **not ** able to register in mDS
 - Wireshark capture: [capture_fails.zip](https://github.com/ARMmbed/mbed-thread-jn517x-example/files/128253/capture_fails.zip)
 - Script to reproduce: [mbed_thread_minimal_build_fails.txt](https://github.com/ARMmbed/mbed-thread-jn517x-example/files/128254/mbed_thread_minimal_build_fails.txt)

* Case 2: JN5x end-node does register in mDS after a while, when printf is added in minar (https://github.com/mlnx/minar/commit/8872f4dd5805b2b585cac0ac00bac366107135fd)
 - Wireshark capture: [capture_works.zip](https://github.com/ARMmbed/mbed-thread-jn517x-example/files/128255/capture_works.zip)
 - Script to reproduce: [mbed_thread_minimal_build_works.txt](https://github.com/ARMmbed/mbed-thread-jn517x-example/files/128256/mbed_thread_minimal_build_works.txt)

![mds_thread_reg](https://cloud.githubusercontent.com/assets/1931553/13013021/984706c0-d1a5-11e5-954a-1f1d020f66ba.png)

@SeppoTakalo could you please have a look and reproduce in your office?

**Comment by SeppoTakalo** [comment] 2016-02-15 16:56
@mlnx I tried that the mbed_thread_minimal_build_works.bat is able to produce binary that tries to join the network and even try to register with mDS. I then replaced the sal-stack-nanostack with the public release and it also joined the network and is trying to register.

**Comment by SeppoTakalo** [comment] 2016-02-16 12:30
I tried this issue also with https://github.com/ARMmbed/sal-stack-nanostack-eventloop/issues/18 and it did not change the behaviour.

**Comment by LiyouZhou** [comment] 2016-02-29 17:47
I see on the node, after a while, the code gets stuck in this while loop: https://github.com/ARMmbed/mbed-hal-nxp-jn517x/blob/dev_nxp_main/source/lp_ticker.c#L79

**Comment by SeppoTakalo** [comment] 2016-02-29 18:36
Really good finding!
Not sure what this register does, but sound like it is some kind of interrupt mask register. So probably a interrupt happened while it was clearing a flag, therefore it keeps polling.
How about if you modify the code to something like this:
~~~
/* Clear existing interrupt */
    while ((u32REG_SysRead(REG_SYS_WK_ES) & mask) != 0)
	vREG_SysReadModWrite32(REG_SYS_WK_ES, mask, 0);
~~~

But that is just a guess. Somebody with knowledge of this uC should be able to answer what is the proper way to fix this.

**Comment by mlnx** [comment] 2016-02-29 18:50
cc @bangaragirinxp could you please comment on this issue?

**Comment by bangaragirinxp** [comment] 2016-03-01 04:03
The code clears the interrupt status & wait till the interrupt bit is cleared in the register.
Can you please let me the steps to reproduce the issue? 
Did you add any prints in the while loop to observe that the code is stuck in the loop?

**Comment by bangaragirinxp** [comment] 2016-03-01 04:37
In register REG_SYS_WK_ES, we have to write 1 to clear the bit & writing 0 will not have any effect. We have fixed the issue by changing vREG_SysReadModWrite32 to vREG_SysWrite to correctly clear the interrupt status. The changes are committed in GitHub code. Can you please check with the updated fix?

**Comment by mlnx** [comment] 2016-03-03 15:00
The issue was found using a debugger and checking where the application was stuck.

We think minar is now working fine, as the timer is being initialized correctly.
We'll close this for now and may re-open if required (other issues are going to be tracked separetely).

**Closed** 2016-03-03 15:00 UTC
